(define (problem p1) ;Problema para comprobar el primer cambio de fase
(:domain Agricola)
(:objects arar bosque - accion)
(:INIT
  (nextFase one two)(nextFase two three)(nextFase three four)
  (actualRonda one)
  (actualFase one)
  (disponible bosque)
  (acumulable bosque madera)
  (desbloquear arar one)
  (nextRonda one two)
  (maxRonda two)
  (maxFase three one)
  (= (almacenRecursoJug madera jugadorUno) 0)
  (= (almacenRecursoJug madera jugadorDos) 0)
)
(:goal
  (fin)
)
)
